# Generated by Django 4.0.6 on 2022-07-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=25, null=True)),
                ('name', models.CharField(max_length=350, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('num_of_ratings', models.IntegerField(null=True)),
                ('shipping', models.CharField(max_length=25, null=True)),
                ('promotion', models.CharField(max_length=150, null=True)),
                ('out_of_stock', models.BooleanField()),
                ('item_id', models.CharField(max_length=25)),
            ],
        ),
    ]
