# Generated by Django 4.0.6 on 2023-09-09 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_id',
        ),
    ]
